config/routes.rb
Rails.application.routes.draw do
  resources :picts

 root 'picts#index'

end

app/models/pict.rb
class Pict < ActiveRecord::Base
  has_attached_file :photo, :styles => { :small => "300x300>", :middle => "600x600" },
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 10.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png', 'image/gif']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/picts_controller.rb
class PictsController < ApplicationController
  before_action :set_pict, only: [:show, :edit, :update, :destroy]

  # GET /picts
  # GET /picts.json
  def index
    @picts = Pict.paginate(:page => params[:page], :per_page => 18).order('created_at DESC')

  end

  # GET /picts/1
  # GET /picts/1.json
  def show
  end

  # GET /picts/new
  def new
    @pict = Pict.new
  end

  # GET /picts/1/edit
  def edit
  end

  # POST /picts
  # POST /picts.json
  def create
    @pict = Pict.new(pict_params)

    respond_to do |format|
      if @pict.save
        format.html { redirect_to @pict, notice: 'Pict was successfully created.' }
        format.json { render :show, status: :created, location: @pict }
      else
        format.html { render :new }
        format.json { render json: @pict.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /picts/1
  # PATCH/PUT /picts/1.json
  def update
    respond_to do |format|
      if @pict.update(pict_params)
        format.html { redirect_to @pict, notice: 'Pict was successfully updated.' }
        format.json { render :show, status: :ok, location: @pict }
      else
        format.html { render :edit }
        format.json { render json: @pict.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picts/1
  # DELETE /picts/1.json
  def destroy
    @pict.destroy
    respond_to do |format|
      format.html { redirect_to picts_url, notice: 'Pict was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pict
      @pict = Pict.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pict_params
      params.require(:pict).permit(:photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picts_helper.rb
module PictsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pictuploader</title>


  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/picts/_form.html.erb
<%= form_for(@pict) do |f| %>
  <% if @pict.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pict.errors.count, "error") %> prohibited this pict from being saved:</h2>

      <ul>
      <% @pict.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :photo %><br>
  <%= f.file_field :photo%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/picts/edit.html.erb
<h1>Editing pict</h1>
<%= image_tag @pict.photo.url(:small) %>

<%= render 'form' %>

<%= link_to 'Show', @pict %> 
<%= link_to 'Back', picts_path %>

app/views/picts/index.html.erb
<h1>Mes Images</h1>

<!-- <table> -->
<!--   <thead> -->
<!--     <tr> -->
<!--       <th>Photo</th> -->
<!--       <th colspan="3"></th> -->
<!--     </tr> -->
<!--   </thead> -->
<%= link_to 'New Pict', new_pict_path,:class => "add" %>
<div class="corps">

<%= will_paginate @picts %>

    <% @picts.each do |pict| %>
<div class="thumbnails" style="background:url( '<%=pict.photo.url(:small)%>') no-repeat scroll center center rgba(0, 0, 0, 0.1)";>
  <%= link_to '', pict,:class =>"show" %>
   <!--  <div class="bouton destroy"><%= link_to 'X', pict, method: :delete, data: { confirm: 'Are you sure?' }%></div> -->
    <div class="bouton link"><%=link_to "taille réelle", pict.photo.url%><%=link_to "taille moyenne", pict.photo.url(:middle)%><%=link_to "taille small", pict.photo.url(:small)%></div>
   <!-- <%= link_to 'Edit', edit_pict_path(pict)  %></div> -->


</div>

<!--       <tr> -->
<!--         <td><%= image_tag pict.photo.url(:small) if pict.photo? %></td> -->

<!--         <td><%= link_to 'Show', pict %></td> -->
<!--         <td><%= link_to 'Edit', edit_pict_path(pict) %></td> -->
<!--         <td><%= link_to 'Destroy', pict, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
<!--       </tr> -->
 <% end %> 
<!--   </tbody> -->
<!-- </table> -->
</div>

app/views/picts/new.html.erb
<h1>New pict</h1>

<%= render 'form' %>

<%= link_to 'Back', picts_path %>

app/views/picts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo:</strong>
<%= image_tag @pict.photo.url %>


</p>

<%= link_to 'Edit', edit_pict_path(@pict) %> 
<%= link_to 'Back', picts_path %>
<%= link_to 'Destroy', @pict, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"destroy" %>